/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: cometbft/services/version/v1/version_service.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./version";
import * as grpc_1 from "@grpc/grpc-js";
export namespace cometbft.services.version.v1 {
    interface GrpcUnaryServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    }
    interface GrpcStreamServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
        (message: P, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
    }
    interface GrpWritableServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
    }
    interface GrpcChunkServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
        (options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
    }
    interface GrpcPromiseServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): Promise<R>;
        (message: P, options?: grpc_1.CallOptions): Promise<R>;
    }
    export abstract class UnimplementedVersionServiceService {
        static definition = {
            GetVersion: {
                path: "/cometbft.services.version.v1.VersionService/GetVersion",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_1.cometbft.services.version.v1.GetVersionRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_1.cometbft.services.version.v1.GetVersionRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.cometbft.services.version.v1.GetVersionResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.cometbft.services.version.v1.GetVersionResponse.deserialize(new Uint8Array(bytes))
            }
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract GetVersion(call: grpc_1.ServerUnaryCall<dependency_1.cometbft.services.version.v1.GetVersionRequest, dependency_1.cometbft.services.version.v1.GetVersionResponse>, callback: grpc_1.sendUnaryData<dependency_1.cometbft.services.version.v1.GetVersionResponse>): void;
    }
    export class VersionServiceClient extends grpc_1.makeGenericClientConstructor(UnimplementedVersionServiceService.definition, "VersionService", {}) {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
            super(address, credentials, options);
        }
        GetVersion: GrpcUnaryServiceInterface<dependency_1.cometbft.services.version.v1.GetVersionRequest, dependency_1.cometbft.services.version.v1.GetVersionResponse> = (message: dependency_1.cometbft.services.version.v1.GetVersionRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.cometbft.services.version.v1.GetVersionResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.cometbft.services.version.v1.GetVersionResponse>, callback?: grpc_1.requestCallback<dependency_1.cometbft.services.version.v1.GetVersionResponse>): grpc_1.ClientUnaryCall => {
            return super.GetVersion(message, metadata, options, callback);
        };
    }
}
