// source: band/feeds/v1beta1/tx.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

var gogoproto_gogo_pb = require('../../../gogoproto/gogo_pb.js');
goog.object.extend(proto, gogoproto_gogo_pb);
var band_feeds_v1beta1_feeds_pb = require('../../../band/feeds/v1beta1/feeds_pb.js');
goog.object.extend(proto, band_feeds_v1beta1_feeds_pb);
var band_feeds_v1beta1_params_pb = require('../../../band/feeds/v1beta1/params_pb.js');
goog.object.extend(proto, band_feeds_v1beta1_params_pb);
var cosmos_proto_cosmos_pb = require('../../../cosmos_proto/cosmos_pb.js');
goog.object.extend(proto, cosmos_proto_cosmos_pb);
var cosmos_msg_v1_msg_pb = require('../../../cosmos/msg/v1/msg_pb.js');
goog.object.extend(proto, cosmos_msg_v1_msg_pb);
var amino_amino_pb = require('../../../amino/amino_pb.js');
goog.object.extend(proto, amino_amino_pb);
goog.exportSymbol('proto.band.feeds.v1beta1.MsgSubmitSignalPrices', null, global);
goog.exportSymbol('proto.band.feeds.v1beta1.MsgSubmitSignalPricesResponse', null, global);
goog.exportSymbol('proto.band.feeds.v1beta1.MsgUpdateParams', null, global);
goog.exportSymbol('proto.band.feeds.v1beta1.MsgUpdateParamsResponse', null, global);
goog.exportSymbol('proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfig', null, global);
goog.exportSymbol('proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfigResponse', null, global);
goog.exportSymbol('proto.band.feeds.v1beta1.MsgVote', null, global);
goog.exportSymbol('proto.band.feeds.v1beta1.MsgVoteResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.band.feeds.v1beta1.MsgVote = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.band.feeds.v1beta1.MsgVote.repeatedFields_, null);
};
goog.inherits(proto.band.feeds.v1beta1.MsgVote, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.band.feeds.v1beta1.MsgVote.displayName = 'proto.band.feeds.v1beta1.MsgVote';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.band.feeds.v1beta1.MsgVoteResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.band.feeds.v1beta1.MsgVoteResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.band.feeds.v1beta1.MsgVoteResponse.displayName = 'proto.band.feeds.v1beta1.MsgVoteResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.band.feeds.v1beta1.MsgSubmitSignalPrices = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.band.feeds.v1beta1.MsgSubmitSignalPrices.repeatedFields_, null);
};
goog.inherits(proto.band.feeds.v1beta1.MsgSubmitSignalPrices, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.band.feeds.v1beta1.MsgSubmitSignalPrices.displayName = 'proto.band.feeds.v1beta1.MsgSubmitSignalPrices';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.band.feeds.v1beta1.MsgSubmitSignalPricesResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.band.feeds.v1beta1.MsgSubmitSignalPricesResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.band.feeds.v1beta1.MsgSubmitSignalPricesResponse.displayName = 'proto.band.feeds.v1beta1.MsgSubmitSignalPricesResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfig.displayName = 'proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfig';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfigResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfigResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfigResponse.displayName = 'proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfigResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.band.feeds.v1beta1.MsgUpdateParams = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.band.feeds.v1beta1.MsgUpdateParams, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.band.feeds.v1beta1.MsgUpdateParams.displayName = 'proto.band.feeds.v1beta1.MsgUpdateParams';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.band.feeds.v1beta1.MsgUpdateParamsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.band.feeds.v1beta1.MsgUpdateParamsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.band.feeds.v1beta1.MsgUpdateParamsResponse.displayName = 'proto.band.feeds.v1beta1.MsgUpdateParamsResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.band.feeds.v1beta1.MsgVote.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.band.feeds.v1beta1.MsgVote.prototype.toObject = function(opt_includeInstance) {
  return proto.band.feeds.v1beta1.MsgVote.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.band.feeds.v1beta1.MsgVote} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.band.feeds.v1beta1.MsgVote.toObject = function(includeInstance, msg) {
  var f, obj = {
    voter: jspb.Message.getFieldWithDefault(msg, 1, ""),
    signalsList: jspb.Message.toObjectList(msg.getSignalsList(),
    band_feeds_v1beta1_feeds_pb.Signal.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.band.feeds.v1beta1.MsgVote}
 */
proto.band.feeds.v1beta1.MsgVote.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.band.feeds.v1beta1.MsgVote;
  return proto.band.feeds.v1beta1.MsgVote.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.band.feeds.v1beta1.MsgVote} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.band.feeds.v1beta1.MsgVote}
 */
proto.band.feeds.v1beta1.MsgVote.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setVoter(value);
      break;
    case 2:
      var value = new band_feeds_v1beta1_feeds_pb.Signal;
      reader.readMessage(value,band_feeds_v1beta1_feeds_pb.Signal.deserializeBinaryFromReader);
      msg.addSignals(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.band.feeds.v1beta1.MsgVote.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.band.feeds.v1beta1.MsgVote.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.band.feeds.v1beta1.MsgVote} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.band.feeds.v1beta1.MsgVote.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getVoter();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSignalsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      band_feeds_v1beta1_feeds_pb.Signal.serializeBinaryToWriter
    );
  }
};


/**
 * optional string voter = 1;
 * @return {string}
 */
proto.band.feeds.v1beta1.MsgVote.prototype.getVoter = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.band.feeds.v1beta1.MsgVote} returns this
 */
proto.band.feeds.v1beta1.MsgVote.prototype.setVoter = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated Signal signals = 2;
 * @return {!Array<!proto.band.feeds.v1beta1.Signal>}
 */
proto.band.feeds.v1beta1.MsgVote.prototype.getSignalsList = function() {
  return /** @type{!Array<!proto.band.feeds.v1beta1.Signal>} */ (
    jspb.Message.getRepeatedWrapperField(this, band_feeds_v1beta1_feeds_pb.Signal, 2));
};


/**
 * @param {!Array<!proto.band.feeds.v1beta1.Signal>} value
 * @return {!proto.band.feeds.v1beta1.MsgVote} returns this
*/
proto.band.feeds.v1beta1.MsgVote.prototype.setSignalsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.band.feeds.v1beta1.Signal=} opt_value
 * @param {number=} opt_index
 * @return {!proto.band.feeds.v1beta1.Signal}
 */
proto.band.feeds.v1beta1.MsgVote.prototype.addSignals = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.band.feeds.v1beta1.Signal, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.band.feeds.v1beta1.MsgVote} returns this
 */
proto.band.feeds.v1beta1.MsgVote.prototype.clearSignalsList = function() {
  return this.setSignalsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.band.feeds.v1beta1.MsgVoteResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.band.feeds.v1beta1.MsgVoteResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.band.feeds.v1beta1.MsgVoteResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.band.feeds.v1beta1.MsgVoteResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.band.feeds.v1beta1.MsgVoteResponse}
 */
proto.band.feeds.v1beta1.MsgVoteResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.band.feeds.v1beta1.MsgVoteResponse;
  return proto.band.feeds.v1beta1.MsgVoteResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.band.feeds.v1beta1.MsgVoteResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.band.feeds.v1beta1.MsgVoteResponse}
 */
proto.band.feeds.v1beta1.MsgVoteResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.band.feeds.v1beta1.MsgVoteResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.band.feeds.v1beta1.MsgVoteResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.band.feeds.v1beta1.MsgVoteResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.band.feeds.v1beta1.MsgVoteResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.band.feeds.v1beta1.MsgSubmitSignalPrices.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.band.feeds.v1beta1.MsgSubmitSignalPrices.prototype.toObject = function(opt_includeInstance) {
  return proto.band.feeds.v1beta1.MsgSubmitSignalPrices.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.band.feeds.v1beta1.MsgSubmitSignalPrices} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.band.feeds.v1beta1.MsgSubmitSignalPrices.toObject = function(includeInstance, msg) {
  var f, obj = {
    validator: jspb.Message.getFieldWithDefault(msg, 1, ""),
    timestamp: jspb.Message.getFieldWithDefault(msg, 2, 0),
    signalPricesList: jspb.Message.toObjectList(msg.getSignalPricesList(),
    band_feeds_v1beta1_feeds_pb.SignalPrice.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.band.feeds.v1beta1.MsgSubmitSignalPrices}
 */
proto.band.feeds.v1beta1.MsgSubmitSignalPrices.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.band.feeds.v1beta1.MsgSubmitSignalPrices;
  return proto.band.feeds.v1beta1.MsgSubmitSignalPrices.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.band.feeds.v1beta1.MsgSubmitSignalPrices} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.band.feeds.v1beta1.MsgSubmitSignalPrices}
 */
proto.band.feeds.v1beta1.MsgSubmitSignalPrices.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setValidator(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestamp(value);
      break;
    case 3:
      var value = new band_feeds_v1beta1_feeds_pb.SignalPrice;
      reader.readMessage(value,band_feeds_v1beta1_feeds_pb.SignalPrice.deserializeBinaryFromReader);
      msg.addSignalPrices(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.band.feeds.v1beta1.MsgSubmitSignalPrices.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.band.feeds.v1beta1.MsgSubmitSignalPrices.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.band.feeds.v1beta1.MsgSubmitSignalPrices} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.band.feeds.v1beta1.MsgSubmitSignalPrices.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getValidator();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getSignalPricesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      band_feeds_v1beta1_feeds_pb.SignalPrice.serializeBinaryToWriter
    );
  }
};


/**
 * optional string validator = 1;
 * @return {string}
 */
proto.band.feeds.v1beta1.MsgSubmitSignalPrices.prototype.getValidator = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.band.feeds.v1beta1.MsgSubmitSignalPrices} returns this
 */
proto.band.feeds.v1beta1.MsgSubmitSignalPrices.prototype.setValidator = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int64 timestamp = 2;
 * @return {number}
 */
proto.band.feeds.v1beta1.MsgSubmitSignalPrices.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.band.feeds.v1beta1.MsgSubmitSignalPrices} returns this
 */
proto.band.feeds.v1beta1.MsgSubmitSignalPrices.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * repeated SignalPrice signal_prices = 3;
 * @return {!Array<!proto.band.feeds.v1beta1.SignalPrice>}
 */
proto.band.feeds.v1beta1.MsgSubmitSignalPrices.prototype.getSignalPricesList = function() {
  return /** @type{!Array<!proto.band.feeds.v1beta1.SignalPrice>} */ (
    jspb.Message.getRepeatedWrapperField(this, band_feeds_v1beta1_feeds_pb.SignalPrice, 3));
};


/**
 * @param {!Array<!proto.band.feeds.v1beta1.SignalPrice>} value
 * @return {!proto.band.feeds.v1beta1.MsgSubmitSignalPrices} returns this
*/
proto.band.feeds.v1beta1.MsgSubmitSignalPrices.prototype.setSignalPricesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.band.feeds.v1beta1.SignalPrice=} opt_value
 * @param {number=} opt_index
 * @return {!proto.band.feeds.v1beta1.SignalPrice}
 */
proto.band.feeds.v1beta1.MsgSubmitSignalPrices.prototype.addSignalPrices = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.band.feeds.v1beta1.SignalPrice, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.band.feeds.v1beta1.MsgSubmitSignalPrices} returns this
 */
proto.band.feeds.v1beta1.MsgSubmitSignalPrices.prototype.clearSignalPricesList = function() {
  return this.setSignalPricesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.band.feeds.v1beta1.MsgSubmitSignalPricesResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.band.feeds.v1beta1.MsgSubmitSignalPricesResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.band.feeds.v1beta1.MsgSubmitSignalPricesResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.band.feeds.v1beta1.MsgSubmitSignalPricesResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.band.feeds.v1beta1.MsgSubmitSignalPricesResponse}
 */
proto.band.feeds.v1beta1.MsgSubmitSignalPricesResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.band.feeds.v1beta1.MsgSubmitSignalPricesResponse;
  return proto.band.feeds.v1beta1.MsgSubmitSignalPricesResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.band.feeds.v1beta1.MsgSubmitSignalPricesResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.band.feeds.v1beta1.MsgSubmitSignalPricesResponse}
 */
proto.band.feeds.v1beta1.MsgSubmitSignalPricesResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.band.feeds.v1beta1.MsgSubmitSignalPricesResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.band.feeds.v1beta1.MsgSubmitSignalPricesResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.band.feeds.v1beta1.MsgSubmitSignalPricesResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.band.feeds.v1beta1.MsgSubmitSignalPricesResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    admin: jspb.Message.getFieldWithDefault(msg, 1, ""),
    referenceSourceConfig: (f = msg.getReferenceSourceConfig()) && band_feeds_v1beta1_feeds_pb.ReferenceSourceConfig.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfig}
 */
proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfig;
  return proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfig}
 */
proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAdmin(value);
      break;
    case 2:
      var value = new band_feeds_v1beta1_feeds_pb.ReferenceSourceConfig;
      reader.readMessage(value,band_feeds_v1beta1_feeds_pb.ReferenceSourceConfig.deserializeBinaryFromReader);
      msg.setReferenceSourceConfig(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAdmin();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getReferenceSourceConfig();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      band_feeds_v1beta1_feeds_pb.ReferenceSourceConfig.serializeBinaryToWriter
    );
  }
};


/**
 * optional string admin = 1;
 * @return {string}
 */
proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfig.prototype.getAdmin = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfig} returns this
 */
proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfig.prototype.setAdmin = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional ReferenceSourceConfig reference_source_config = 2;
 * @return {?proto.band.feeds.v1beta1.ReferenceSourceConfig}
 */
proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfig.prototype.getReferenceSourceConfig = function() {
  return /** @type{?proto.band.feeds.v1beta1.ReferenceSourceConfig} */ (
    jspb.Message.getWrapperField(this, band_feeds_v1beta1_feeds_pb.ReferenceSourceConfig, 2));
};


/**
 * @param {?proto.band.feeds.v1beta1.ReferenceSourceConfig|undefined} value
 * @return {!proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfig} returns this
*/
proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfig.prototype.setReferenceSourceConfig = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfig} returns this
 */
proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfig.prototype.clearReferenceSourceConfig = function() {
  return this.setReferenceSourceConfig(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfig.prototype.hasReferenceSourceConfig = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfigResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfigResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfigResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfigResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfigResponse}
 */
proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfigResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfigResponse;
  return proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfigResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfigResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfigResponse}
 */
proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfigResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfigResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfigResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfigResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.band.feeds.v1beta1.MsgUpdateReferenceSourceConfigResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.band.feeds.v1beta1.MsgUpdateParams.prototype.toObject = function(opt_includeInstance) {
  return proto.band.feeds.v1beta1.MsgUpdateParams.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.band.feeds.v1beta1.MsgUpdateParams} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.band.feeds.v1beta1.MsgUpdateParams.toObject = function(includeInstance, msg) {
  var f, obj = {
    authority: jspb.Message.getFieldWithDefault(msg, 1, ""),
    params: (f = msg.getParams()) && band_feeds_v1beta1_params_pb.Params.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.band.feeds.v1beta1.MsgUpdateParams}
 */
proto.band.feeds.v1beta1.MsgUpdateParams.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.band.feeds.v1beta1.MsgUpdateParams;
  return proto.band.feeds.v1beta1.MsgUpdateParams.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.band.feeds.v1beta1.MsgUpdateParams} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.band.feeds.v1beta1.MsgUpdateParams}
 */
proto.band.feeds.v1beta1.MsgUpdateParams.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAuthority(value);
      break;
    case 2:
      var value = new band_feeds_v1beta1_params_pb.Params;
      reader.readMessage(value,band_feeds_v1beta1_params_pb.Params.deserializeBinaryFromReader);
      msg.setParams(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.band.feeds.v1beta1.MsgUpdateParams.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.band.feeds.v1beta1.MsgUpdateParams.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.band.feeds.v1beta1.MsgUpdateParams} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.band.feeds.v1beta1.MsgUpdateParams.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAuthority();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getParams();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      band_feeds_v1beta1_params_pb.Params.serializeBinaryToWriter
    );
  }
};


/**
 * optional string authority = 1;
 * @return {string}
 */
proto.band.feeds.v1beta1.MsgUpdateParams.prototype.getAuthority = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.band.feeds.v1beta1.MsgUpdateParams} returns this
 */
proto.band.feeds.v1beta1.MsgUpdateParams.prototype.setAuthority = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Params params = 2;
 * @return {?proto.band.feeds.v1beta1.Params}
 */
proto.band.feeds.v1beta1.MsgUpdateParams.prototype.getParams = function() {
  return /** @type{?proto.band.feeds.v1beta1.Params} */ (
    jspb.Message.getWrapperField(this, band_feeds_v1beta1_params_pb.Params, 2));
};


/**
 * @param {?proto.band.feeds.v1beta1.Params|undefined} value
 * @return {!proto.band.feeds.v1beta1.MsgUpdateParams} returns this
*/
proto.band.feeds.v1beta1.MsgUpdateParams.prototype.setParams = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.band.feeds.v1beta1.MsgUpdateParams} returns this
 */
proto.band.feeds.v1beta1.MsgUpdateParams.prototype.clearParams = function() {
  return this.setParams(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.band.feeds.v1beta1.MsgUpdateParams.prototype.hasParams = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.band.feeds.v1beta1.MsgUpdateParamsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.band.feeds.v1beta1.MsgUpdateParamsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.band.feeds.v1beta1.MsgUpdateParamsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.band.feeds.v1beta1.MsgUpdateParamsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.band.feeds.v1beta1.MsgUpdateParamsResponse}
 */
proto.band.feeds.v1beta1.MsgUpdateParamsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.band.feeds.v1beta1.MsgUpdateParamsResponse;
  return proto.band.feeds.v1beta1.MsgUpdateParamsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.band.feeds.v1beta1.MsgUpdateParamsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.band.feeds.v1beta1.MsgUpdateParamsResponse}
 */
proto.band.feeds.v1beta1.MsgUpdateParamsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.band.feeds.v1beta1.MsgUpdateParamsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.band.feeds.v1beta1.MsgUpdateParamsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.band.feeds.v1beta1.MsgUpdateParamsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.band.feeds.v1beta1.MsgUpdateParamsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};


goog.object.extend(exports, proto.band.feeds.v1beta1);
