// source: band/tunnel/v1beta1/params.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

var gogoproto_gogo_pb = require('../../../gogoproto/gogo_pb.js');
goog.object.extend(proto, gogoproto_gogo_pb);
var cosmos_base_v1beta1_coin_pb = require('../../../cosmos/base/v1beta1/coin_pb.js');
goog.object.extend(proto, cosmos_base_v1beta1_coin_pb);
goog.exportSymbol('proto.band.tunnel.v1beta1.Params', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.band.tunnel.v1beta1.Params = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.band.tunnel.v1beta1.Params.repeatedFields_, null);
};
goog.inherits(proto.band.tunnel.v1beta1.Params, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.band.tunnel.v1beta1.Params.displayName = 'proto.band.tunnel.v1beta1.Params';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.band.tunnel.v1beta1.Params.repeatedFields_ = [1,7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.band.tunnel.v1beta1.Params.prototype.toObject = function(opt_includeInstance) {
  return proto.band.tunnel.v1beta1.Params.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.band.tunnel.v1beta1.Params} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.band.tunnel.v1beta1.Params.toObject = function(includeInstance, msg) {
  var f, obj = {
    minDepositList: jspb.Message.toObjectList(msg.getMinDepositList(),
    cosmos_base_v1beta1_coin_pb.Coin.toObject, includeInstance),
    minInterval: jspb.Message.getFieldWithDefault(msg, 2, 0),
    maxInterval: jspb.Message.getFieldWithDefault(msg, 3, 0),
    minDeviationBps: jspb.Message.getFieldWithDefault(msg, 4, 0),
    maxDeviationBps: jspb.Message.getFieldWithDefault(msg, 5, 0),
    maxSignals: jspb.Message.getFieldWithDefault(msg, 6, 0),
    basePacketFeeList: jspb.Message.toObjectList(msg.getBasePacketFeeList(),
    cosmos_base_v1beta1_coin_pb.Coin.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.band.tunnel.v1beta1.Params}
 */
proto.band.tunnel.v1beta1.Params.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.band.tunnel.v1beta1.Params;
  return proto.band.tunnel.v1beta1.Params.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.band.tunnel.v1beta1.Params} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.band.tunnel.v1beta1.Params}
 */
proto.band.tunnel.v1beta1.Params.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new cosmos_base_v1beta1_coin_pb.Coin;
      reader.readMessage(value,cosmos_base_v1beta1_coin_pb.Coin.deserializeBinaryFromReader);
      msg.addMinDeposit(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setMinInterval(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setMaxInterval(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setMinDeviationBps(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setMaxDeviationBps(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setMaxSignals(value);
      break;
    case 7:
      var value = new cosmos_base_v1beta1_coin_pb.Coin;
      reader.readMessage(value,cosmos_base_v1beta1_coin_pb.Coin.deserializeBinaryFromReader);
      msg.addBasePacketFee(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.band.tunnel.v1beta1.Params.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.band.tunnel.v1beta1.Params.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.band.tunnel.v1beta1.Params} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.band.tunnel.v1beta1.Params.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMinDepositList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      cosmos_base_v1beta1_coin_pb.Coin.serializeBinaryToWriter
    );
  }
  f = message.getMinInterval();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getMaxInterval();
  if (f !== 0) {
    writer.writeUint64(
      3,
      f
    );
  }
  f = message.getMinDeviationBps();
  if (f !== 0) {
    writer.writeUint64(
      4,
      f
    );
  }
  f = message.getMaxDeviationBps();
  if (f !== 0) {
    writer.writeUint64(
      5,
      f
    );
  }
  f = message.getMaxSignals();
  if (f !== 0) {
    writer.writeUint64(
      6,
      f
    );
  }
  f = message.getBasePacketFeeList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      7,
      f,
      cosmos_base_v1beta1_coin_pb.Coin.serializeBinaryToWriter
    );
  }
};


/**
 * repeated cosmos.base.v1beta1.Coin min_deposit = 1;
 * @return {!Array<!proto.cosmos.base.v1beta1.Coin>}
 */
proto.band.tunnel.v1beta1.Params.prototype.getMinDepositList = function() {
  return /** @type{!Array<!proto.cosmos.base.v1beta1.Coin>} */ (
    jspb.Message.getRepeatedWrapperField(this, cosmos_base_v1beta1_coin_pb.Coin, 1));
};


/**
 * @param {!Array<!proto.cosmos.base.v1beta1.Coin>} value
 * @return {!proto.band.tunnel.v1beta1.Params} returns this
*/
proto.band.tunnel.v1beta1.Params.prototype.setMinDepositList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.cosmos.base.v1beta1.Coin=} opt_value
 * @param {number=} opt_index
 * @return {!proto.cosmos.base.v1beta1.Coin}
 */
proto.band.tunnel.v1beta1.Params.prototype.addMinDeposit = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.cosmos.base.v1beta1.Coin, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.band.tunnel.v1beta1.Params} returns this
 */
proto.band.tunnel.v1beta1.Params.prototype.clearMinDepositList = function() {
  return this.setMinDepositList([]);
};


/**
 * optional uint64 min_interval = 2;
 * @return {number}
 */
proto.band.tunnel.v1beta1.Params.prototype.getMinInterval = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.band.tunnel.v1beta1.Params} returns this
 */
proto.band.tunnel.v1beta1.Params.prototype.setMinInterval = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint64 max_interval = 3;
 * @return {number}
 */
proto.band.tunnel.v1beta1.Params.prototype.getMaxInterval = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.band.tunnel.v1beta1.Params} returns this
 */
proto.band.tunnel.v1beta1.Params.prototype.setMaxInterval = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional uint64 min_deviation_bps = 4;
 * @return {number}
 */
proto.band.tunnel.v1beta1.Params.prototype.getMinDeviationBps = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.band.tunnel.v1beta1.Params} returns this
 */
proto.band.tunnel.v1beta1.Params.prototype.setMinDeviationBps = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional uint64 max_deviation_bps = 5;
 * @return {number}
 */
proto.band.tunnel.v1beta1.Params.prototype.getMaxDeviationBps = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.band.tunnel.v1beta1.Params} returns this
 */
proto.band.tunnel.v1beta1.Params.prototype.setMaxDeviationBps = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional uint64 max_signals = 6;
 * @return {number}
 */
proto.band.tunnel.v1beta1.Params.prototype.getMaxSignals = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.band.tunnel.v1beta1.Params} returns this
 */
proto.band.tunnel.v1beta1.Params.prototype.setMaxSignals = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * repeated cosmos.base.v1beta1.Coin base_packet_fee = 7;
 * @return {!Array<!proto.cosmos.base.v1beta1.Coin>}
 */
proto.band.tunnel.v1beta1.Params.prototype.getBasePacketFeeList = function() {
  return /** @type{!Array<!proto.cosmos.base.v1beta1.Coin>} */ (
    jspb.Message.getRepeatedWrapperField(this, cosmos_base_v1beta1_coin_pb.Coin, 7));
};


/**
 * @param {!Array<!proto.cosmos.base.v1beta1.Coin>} value
 * @return {!proto.band.tunnel.v1beta1.Params} returns this
*/
proto.band.tunnel.v1beta1.Params.prototype.setBasePacketFeeList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 7, value);
};


/**
 * @param {!proto.cosmos.base.v1beta1.Coin=} opt_value
 * @param {number=} opt_index
 * @return {!proto.cosmos.base.v1beta1.Coin}
 */
proto.band.tunnel.v1beta1.Params.prototype.addBasePacketFee = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 7, opt_value, proto.cosmos.base.v1beta1.Coin, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.band.tunnel.v1beta1.Params} returns this
 */
proto.band.tunnel.v1beta1.Params.prototype.clearBasePacketFeeList = function() {
  return this.setBasePacketFeeList([]);
};


goog.object.extend(exports, proto.band.tunnel.v1beta1);
