name: Bandchain.js Workflow
on: push

jobs:
  bandchain-test:
    runs-on: ubuntu-latest
    env:
      working-directory: .
    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        id: bandchainjs-node-modules-cache
        uses: actions/cache@v1
        with:
          path: ./node_modules
          key: ${{ runner.OS }}-bandchainjs-test-${{ hashFiles('**/yarn.lock') }}-node-v${{ matrix.node-version }}

      - name: Install modules
        working-directory: ${{env.working-directory}}
        if: steps.bandchainjs-node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Run tests
        working-directory: ${{env.working-directory}}
        run: yarn test
